### ISSUE TITLE
Add caching to make prevent timeouts on installation of dependencies

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/vscode-lingua-franca#108]
@petervdonovan do you know what is causing these timeouts that render CI super flaky? I would need to know which directories to cache...

**Comment by petervdonovan** [comment]
IIRC it is `pip`. I do not remember which directories this corresponds to.

I'm not sure how caching will work for us because the point of the test which is flaking is that the dependency is not installed.

Perhaps a more pragmatic solution is to change the triggers of this test so that we run it manually instead of automatically. It is likely that most changes will not affect the functionality that is related to this test.

**Comment by lhstrh** [comment]
> Perhaps a more pragmatic solution is to change the triggers of this test so that we run it manually instead of automatically. It is likely that most changes will not affect the functionality that is related to this test.

I think you did this, right? Shall we close this issue then?

**Comment by petervdonovan** [comment]
Yes, you're right. This is closed by #117.
