### ISSUE TITLE
Diagrams bug

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/vscode-lingua-franca#113]
Initial error:
```
klighd-vscode.setLanguageClient command called with invalid arguments.
Please refer to the documentation for reference about the correct usage.
```
After that:
```
command 'klighd-vscode.diagram.open' not found
```

**Comment by soerendomroes** [comment]
You recently changed the import of the language client in your extension. Are you sure that the language client you are using is compatible to the one klighd-vscode needs?

Since when does this occur?

**Comment by lhstrh** [comment]
I'm running the latest version from `main`. I just rebuilt, and now I don't get an error, just an empty screen..

**Comment by lhstrh** [comment]
> You recently changed the import of the language client in your extension. Are you sure that the language client you are using is compatible to the one klighd-vscode needs?

I'm unsure what you mean by this. Could you be more specific?

**Comment by soerendomroes** [comment]
In your extension.ts you call klighd-vscode.setLanguageClient with a languageClient imported from `@vscode/languageclient/node` and the file extension for Lingua Franca "lf". I am unsure whether this language client is still compatible with the language client the KLighD Diagrams extension expects since you are using a more recent vscode version and potentially changed the source of the import from "@vscode/languageclient" to the path above.

**Comment by lhstrh** [comment]
OK, we'll look into this. Thanks for the pointer, @soerendomroes!
