### ISSUE TITLE
Strange rendering artifacts in diagrams

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/vscode-lingua-franca#31]
![image](https://user-images.githubusercontent.com/19938940/160549011-45c39a99-c5a2-4c09-8e50-41f6c333e3bc.png)

**Comment by a-sr** [comment]
This is a discrepancy in the handling of the background color on edges between Klighd rendering in Eclipse and VSC.
[LF PR #1063](https://github.com/lf-lang/lingua-franca/pull/1063) adds a workaround.

**Comment by a-sr** [comment]
Ok, I included a fix for cycle highlighting in the PR as well.
However, I only checked that there is no background color set on the edges (which apparently causes the problem), I could not check the result in VSC because I currently don't have a working setup. You may want to confirm that the rendering artifacts are gone. Or just merge the PR in good hope.

**Comment by lhstrh** [comment]
I've checked with the `v1.0.1` release candidate, which is built against the `v0.1.0` release candidate (up-to-date with `master` currently), but the issue still persists:

![image](https://user-images.githubusercontent.com/19938940/162841658-749f25c7-5483-4251-976f-e41cf2d04f12.png)

**Comment by lhstrh** [comment]
Same with the cycle highlighting: 
![image](https://user-images.githubusercontent.com/19938940/162842305-54fa5f21-9253-4bda-a40a-d1ad19257e07.png)
