### ISSUE TITLE
`npm install` installs the first `.vsix` file it can find rather than the one it produced

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/vscode-lingua-franca#73]
Because we use a wildcard when finding the `.vsix` file, if there is a previously built version, that version gets installed instead of the latest.

**Comment by petervdonovan** [comment]
The previously built VSIX [should be deleted by `npm install` in the `clean` step](https://github.com/lf-lang/vscode-lingua-franca/blob/fd6c80a540a380a4fc7ff2b4ab5dbd8081875681/package.json#L152). Did you observe this issue on the current version of `main`?

It should be easy to fix this by finding the latest version, but I just want to double check so that we don't do redundant work.

**Comment by lhstrh** [comment]
Yes, I observed it on the current version of main.
