### ISSUE TITLE
Compatibility with Github.dev

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/vscode-lingua-franca#78]
Our extension is not compatible with Web use: https://code.visualstudio.com/docs/editor/vscode-web#_extensions

Is this a fundamental issue, or are there ways to make our extension compatible?

On a related note, I found this blog post that talk about how Code Spaces on GitHub compares to GitPod: https://www.freecodecamp.org/news/github-codespaces-vs-gitpod-cloud-based-dev-environments/

**Comment by axmmisaka** [comment]
This is a fundamental issue; some of our plugin relies on Java-based LSP which certainly cannot run in an isolated browser environment
https://github.com/lf-lang/vscode-lingua-franca/blob/e381b4f3dd56b31e441d82160a8b8eb93d58a7aa/src/extension.ts#L90-L92

We could make our extension compatible, if I understand it correctly, by making it give partial IntelliSense support (https://code.visualstudio.com/docs/nodejs/working-with-javascript#_partial-intellisense-mode) (I don't know how exactly to do that), because our syntax highlighter seems to be 100% ts native and should be able to run within a browser

**Comment by lhstrh** [comment]
I see. However, if we don't get full functionality (i.e., we cannot build programs) then I don't think it will be very useful...

**Comment by petervdonovan** [comment]
It seems like work has been done on this: https://github.com/axmmisaka/lingua-franca-playground/tree/axmmisaka/codespace

Can we close this issue? Or does more need to be done with Codespaces or GitPod?

**Comment by lhstrh** [comment]
GitPod and github.dev are two different things. That said, there really isn't much actionable here, so let's close this issue.
