### ISSUE TITLE
Code helper hangs

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/vscode-lingua-franca#88]
Every once in a while, the VS Code helper on my Mac goes into an infinite loop using 100% of CPU and hanging. Code displays a box offering to reopen and the Activity Monitor shows 100% usage:
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/8513334/203589880-0093a186-a528-4217-b489-90fe26f37af9.png">

**Comment by edwardalee** [comment]
A bit more information. This happened again, but now it was `cpptools` hanging. Killing the process resulted in this:
<img width="583" alt="image" src="https://user-images.githubusercontent.com/8513334/203627521-72e53ae0-d40f-4d96-ad88-8876d2c53142.png">

**Comment by petervdonovan** [comment]
This seems like these might be two separate bugs. Code helper apparently has multiple GitHub issues that either are open or that got closed without resolution. https://github.com/microsoft/vscode/issues/148226 is an example. It seems like this problem might be macOS-specific. There is a lot of discussion about it in the internet apparently, including a possible workaround [here](https://stackoverflow.com/questions/71516186/vs-code-uses-100-cpu-even-if-it-is-closed).

I'm not entirely sure whether code helper is related to anything we do since the only mentions I could find of it are these bug reports :sweat_smile:. But definitely the problem with `cpptools` is not our issue, since our language server does not and probably will not ever interact with `cpptools`, except by creating CMakeLists.txt files that confuse it.

**Comment by edwardalee** [comment]
Ok, let's close this then.
